library(shiny)
library(DT)
library(bslib)
library(broom)
library(ggplot2)
library(base64enc)
library(shinyjs)
library(mgcv)
library(RColorBrewer)
library(tidyr)
library(purrr)
library(agricolae)
library(drc)
library(cowplot)
library(MASS)
library(Matrix)
library(shinyjs)
library(equatiomatic)

if (Sys.getenv("RUN_MODE") == "SERVER") {
  library(COMELN)
}
