proxy:
  title: Biostats
  port: 8080
  authentication: none
  hide-navbar: true
  landing-page: SingleApp

  docker:
    internal-networking: true

  specs:
    - id: biostats
      display-name: Biostats
      container-image: konradkraemer/biostats:latest
      container-cmd: ["Rscript", "/srv/shiny-server/app.R"]
      container-env:
        RAW_QUERY: "{{request.queryString}}"
      container-network: sp-net

server:
  forward-headers-strategy: native

