# files <- list.files("/home/konrad/Documents/Biostats/bs/R/", pattern = ".R", full.names = TRUE)
# file.copy(files, "/home/konrad/Documents/Biostats/app/", overwrite = TRUE)

file.create("/home/konrad/Documents/Biostats/app/app.R", overwrite = TRUE)
con <- file("/home/konrad/Documents/Biostats/app/app.R")
code <- function() {
  library(shiny)
  library(shinyWidgets)
  library(DT)
  library(bslib)
  library(broom)
  library(ggplot2)
  library(base64enc)
  library(mgcv)
  library(RColorBrewer)
  library(tidyr)
  library(purrr)
  library(agricolae)
  library(drc)
  library(cowplot)
  library(MASS)
  library(Matrix)
  library(shinyjs)
  library(equatiomatic)
  library(car)
  files <- list.files(".")
  lapply(files, source)
  Sys.setenv(RUN_MODE = "BROWSER")
  app <- app()
  shiny::runApp(app$ui, app$server)
}
code <- body(code) |> deparse()
code <- code[2:(length(code) - 1)]
writeLines(code, con)
close(con)

setwd("/home/konrad/Documents/Biostats")
shinylive::export(appdir = "./app/", destdir = "docs", quiet = FALSE)
setwd("/home/konrad/Documents/Biostats/docs")
httpuv::runStaticServer(".")
