library(shiny)
library(DT)
library(bslib)
library(broom)
library(ggplot2)
library(base64enc)
library(shinyjs)
library(mgcv)
library(RColorBrewer)
library(tidyr)
library(purrr)
library(agricolae)
library(drc)
library(cowplot)
library(MASS)
library(Matrix)
library(shinyjs)
library(equatiomatic)
library(openxlsx)
library(car)
library(cowplot)
library(COMELN)
library(httr)
library(jose)
library(openssl)
library(emmeans)
Sys.setenv(RUN_MODE = "LOCAL")
if (!grepl("R", getwd())) setwd("bs/R")
options(shiny.launch.browser = TRUE)
files <- list.files(".")
trash <- lapply(files, source)
app <- app()
shiny::shinyApp(app$ui, app$server)
