    library(shiny)
    library(shinyWidgets)
    library(DT)
    library(bslib)
    library(broom)
    library(ggplot2)
    library(base64enc)
    library(mgcv)
    library(RColorBrewer)
    library(tidyr)
    library(purrr)
    library(agricolae)
    library(drc)
    library(cowplot)
    library(MASS)
    library(Matrix)
    library(shinyjs)
    library(equatiomatic)
    library(car)
    files <- list.files(".", full.names = TRUE)
    files <- files[!(basename(files) %in% c("app.R", "www"))]
    lapply(files, source)
    Sys.setenv(RUN_MODE = "BROWSER")
    app <- app()
    shiny::shinyApp(app$ui, app$server)

