library(shinytest2)
library(tinytest)
wait <- function(app) {
  try(app$wait_for_idle(), silent = TRUE)
}
app <- bs:::app()
app <- shiny::shinyApp(app$ui, app$server)
app <- AppDriver$new(app)
wait(app)
app$upload_file(
  file = system.file("/test_data/CO2.csv", package = "bs")
)
wait(app)
app$set_window_size(width = 2259, height = 1326)
wait(app)
app$set_inputs(conditionedPanels = "Correlation")
wait(app)
app$click("open_formula_editor")
wait(app)
app$set_inputs(`FO-colnames-dropdown_` = "uptake")
wait(app)
app$click("FO-colnames_conc_")
wait(app)
app$click("FO-create_formula")
wait(app)
app$run_js("$('.modal-footer button:contains(\"Close\")').click();")
wait(app)
app$click("CORR-pear")
wait(app)
res <- app$get_values()$export
wait(app)
expected <- cor.test(CO2$uptake, CO2$conc, method = "pearson")
expected <- broom::tidy(expected)
tinytest::expect_equal(res[["FO-result_list"]][[3]], expected)

app$click("CORR-spear")
wait(app)
res <- app$get_values()$export
wait(app)
expected <- cor.test(CO2$uptake, CO2$conc, method = "spearman")
expected <- broom::tidy(expected)
tinytest::expect_equal(res[["FO-result_list"]][[4]], expected)

app$click("CORR-kendall")
wait(app)
res <- app$get_values()$export
wait(app)
expected <- cor.test(CO2$uptake, CO2$conc, method = "kendall")
expected <- broom::tidy(expected)
tinytest::expect_equal(res[["FO-result_list"]][[5]], expected)

wait(app)
app$stop()
