library(shinytest2)
library(tinytest)
app <- bs::app()
app <- shiny::shinyApp(app$ui, app$server)
app <- AppDriver$new(app)
app$wait_for_idle()
app$upload_file(
  file = system.file("/test_data/CO2.csv", package = "bs")
)
app$wait_for_idle()
app$set_window_size(width = 2259, height = 1326)
app$wait_for_idle()
app$set_inputs(conditionedPanels = "Correlation")
app$wait_for_idle()
app$click("open_formula_editor")
app$wait_for_idle()
app$set_inputs(`FO-colnames-dropdown_0` = "uptake")
app$wait_for_idle()
app$click("FO-colnames_conc_0")
app$wait_for_idle()
app$click("FO-create_formula_V1_2")
app$wait_for_idle()
app$run_js("$('.modal-footer button:contains(\"Close\")').click();")
app$wait_for_idle()
app$click("CORR-pear")
app$wait_for_idle()
res <- app$get_values()$export
app$wait_for_idle()
expected <- cor.test(CO2$uptake, CO2$conc, method = "pearson")
expected <- broom::tidy(expected)
tinytest::expect_equal(res[[1]], expected)
app$click("CORR-spear")
app$wait_for_idle()
res <- app$get_values()$export
app$wait_for_idle()
expected <- cor.test(CO2$uptake, CO2$conc, method = "spearman")
expected <- broom::tidy(expected)
tinytest::expect_equal(res[[1]], expected)
app$click("CORR-kendall")
app$wait_for_idle()
res <- app$get_values()$export
app$wait_for_idle()
expected <- cor.test(CO2$uptake, CO2$conc, method = "kendall")
expected <- broom::tidy(expected)
tinytest::expect_equal(res[[1]], expected)
app$wait_for_idle()
app$stop()
